# Generated by Django 4.2.11 on 2024-04-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0006_document_rename_countrycode_usermaster_countrycode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermaster',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
