# Generated by Django 4.2.11 on 2024-04-24 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0007_alter_usermaster_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermaster',
            old_name='email',
            new_name='Email',
        ),
    ]
