# Generated by Django 4.2.11 on 2024-04-24 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0008_rename_email_usermaster_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermaster',
            old_name='Email',
            new_name='email',
        ),
    ]
