# Generated by Django 4.2.11 on 2024-04-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0009_rename_email_usermaster_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='kids',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('kidsproduct', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'kids',
            },
        ),
        migrations.CreateModel(
            name='Men',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('mensproduct', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'men',
            },
        ),
        migrations.CreateModel(
            name='Women',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('womensproduct', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'womens',
            },
        ),
    ]
