# Generated by Django 4.2.11 on 2024-04-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0010_kids_men_women'),
    ]

    operations = [
        migrations.AddField(
            model_name='kids',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Active'), ('0', 'Inactive')], default='1', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='men',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Active'), ('0', 'Inactive')], default='1', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='women',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Active'), ('0', 'Inactive')], default='1', max_length=20, null=True),
        ),
    ]
