# Generated by Django 4.2.11 on 2024-05-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0012_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='product',
        ),
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='products',
            name='lastupdated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
