# Generated by Django 4.2.11 on 2024-05-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0013_remove_products_product_products_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
