# Generated by Django 4.2.11 on 2024-05-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0014_alter_products_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='lastupdated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
